version: '3'

services:

  postgres:
    container_name: postgres
    build: builds/postgres
    image: no42/postgres:glas_hrvatske
    restart: always

    # keep postgresql data on host after container exits
    volumes:
      - postgres:/var/lib/postgresql/data
    env_file:
      - ./config/.env

  redis:
    container_name: redis
    build: builds/redis
    image: no42/redis:glas_hrvatske
    restart: always

    expose:
      - "6379"
    # keep redis data on host after container exits
    volumes:
    - redis:/data

  nginx:
    container_name: nginx
    build: builds/nginx
    image: no42/nginx:glas_hrvatske
    restart: always

    ports:
      - "80:80"
    links:
      - django
    depends_on:
      - django
    volumes:
      - ./config/nginx.template:/etc/nginx/conf.d/nginx.template
      - log:/var/log/nginx/
      - static:/static
    env_file:
      - ./config/.env
    command: /bin/bash -c "envsubst '$$NGINX_SERVER_NAME' < /etc/nginx/conf.d/nginx.template > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;'"

  django:
    container_name: django
    build: app
    image: no42/django:glas_hrvatske

    expose:
      - "8000"
    links:
      - postgres
      - redis
    volumes:
      - ./app:/app
      - log:/app/log
      - static:/static
    env_file:
      - ./config/.env
    command: ./bin/start.sh

  celery:
    container_name: celery
    build: app
    image: no42/celery:glas_hrvatske

    links:
      - postgres
      - redis
    env_file:
      - ./config/.env
    command: ./bin/start_celery.sh


volumes:

  log:
  django:
  postgres:
  redis:
  static: