# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-13 16:50
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid
import web.service


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Algorithm',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, verbose_name='naziv')),
                ('file', models.FileField(upload_to=web.service.upload_path_exe, verbose_name='datoteka za izvršavanje')),
                ('description', models.TextField(blank=True, verbose_name='opis')),
                ('document', models.FileField(blank=True, upload_to=web.service.upload_path_exe, verbose_name='dokumentacija')),
                ('is_active', models.BooleanField(default=True, help_text='Deaktivirati algoritam umjesto brisanja.', verbose_name='aktivno')),
                ('users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='korisnici s pristupom')),
            ],
            options={
                'db_table': 'algorithm',
                'verbose_name': 'algoritam',
                'verbose_name_plural': 'algoritmi',
                'ordering': ('-created',),
            },
        ),
        migrations.CreateModel(
            name='Iteration',
            fields=[
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('input_data', models.FileField(upload_to=web.service.upload_path_input_data, verbose_name='ulazni podaci')),
                ('output_data', models.FileField(blank=True, upload_to='', verbose_name='izlazni podaci')),
                ('status_code', models.SmallIntegerField(blank=True, choices=[(1, 'izvršavanje u tijeku'), (-1, 'neuspješno završeno'), (0, 'uspješno završeno')], default=1, null=True, verbose_name='statusni kod')),
                ('status_message', models.TextField(blank=True, verbose_name='statusna poruka')),
                ('mail_on_completion', models.BooleanField(default=False, verbose_name='pošalji rezultate na mail')),
                ('mailed', models.DateTimeField(null=True, verbose_name='poslano')),
                ('finished', models.DateTimeField(null=True, verbose_name='završetak')),
                ('algorithm', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='web.Algorithm', verbose_name='algoritam')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='korisnik')),
            ],
            options={
                'db_table': 'algorithm_iteration',
                'verbose_name': 'iteracija algoritma',
                'verbose_name_plural': 'iteracije algoritma',
                'ordering': ('-created', 'algorithm'),
            },
        ),
        migrations.CreateModel(
            name='LoginHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('address', models.GenericIPAddressField(verbose_name='adresa logiranja')),
                ('data', models.TextField(verbose_name='dodatni podaci')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='korisnik')),
            ],
            options={
                'db_table': 'login_history',
                'verbose_name': 'unos povijesti logiranja',
                'verbose_name_plural': 'unosi povijesti logiranja',
                'ordering': ('-created',),
            },
        ),
    ]
