# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 15:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='algorithm',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='naziv'),
        ),
    ]
