# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-19 16:36
from __future__ import unicode_literals

from django.db import migrations, models
import web.service


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0003_auto_20170819_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='algorithm',
            name='source',
            field=models.FileField(blank=True, upload_to=web.service.upload_path_exe, verbose_name='datoteka source kȏda'),
        ),
        migrations.AlterField(
            model_name='algorithm',
            name='document',
            field=models.FileField(blank=True, upload_to=web.service.upload_path_exe, verbose_name='datoteka dokumentacije'),
        ),
    ]
