# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-10 14:31
from __future__ import unicode_literals

from django.db import migrations, models
import web.service


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_auto_20170819_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iteration',
            name='input_data',
            field=models.FileField(max_length=511, upload_to=web.service.upload_path_input_data, verbose_name='ulazni podaci'),
        ),
        migrations.AlterField(
            model_name='iteration',
            name='output_data',
            field=models.FileField(blank=True, max_length=511, upload_to='', verbose_name='izlazni podaci'),
        ),
    ]
